name: solar-analyses

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3
  - black = 23.3.0
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - pre-commit
  - scipy
  - tabulate
  - pip:
    - pystan
